name: stopwatch
description: A simply beautiful stopwatch application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  fonts:
    - family: SF-Regular
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf

    - family: SF-Light
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Light.otf

    - family: SF-Thin
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf